### ISSUE TITLE
Include default obsidian theme in list

### ISSUE THREAD

**Issue by ankushg** [selfire1/obsidian-set-mobile-theme#2]
Loving the plugin! Unfortunately it only shows community themes. 

Any way to have it also show the default Obsidian theme?

**Comment by Zachatoo** [comment]
I'd also like this, though I did find a workaround that I'm happy with. On desktop, navigate to Settings - Appearance - Themes - Manage. Set your theme to the default theme. That will unselect whatever theme was selected on desktop for this plugin.

**Comment by imed-ghomari** [comment]
+1 for this

**Comment by selfire1** [comment]
Included in [0.2.0](https://github.com/selfire1/obsidian-set-mobile-theme/releases/tag/0.2.0).
